# Generated by Django 5.2.7 on 2026-01-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('interviewing', 'interviewing'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending'),
        ),
    ]
