# Generated by Django 5.2.7 on 2026-01-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': [('can_create_application', 'Can Create Application')]},
        ),
    ]
