# Generated by Django 5.2.7 on 2026-03-25 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_options'),
        ('jobs', '0002_alter_job_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'applicant'], name='application_job_id_53c719_idx'),
        ),
    ]
